name: classic-ondra
version: 16.04-0.8
summary: classic gadget package
icon: icon.png
description: |
 This package contains a simple OEM snappy package for system configuration
type: gadget
architectures:
    - amd64
    - armhf
    - arm64
confinement: strict
grade: stable
parts:
    snap:
        plugin: dump
        organize:
        source: hooks
        organize:
            prepare-device: meta/hooks/prepare-device
